return {
    GameName = "Place1",
    ExperienceName = "Place1",
    Architecture = "terrain-first-v1",
    Author = "Mikey",
    Version = "0.1",
    GroupId = 846021713,
    GroupName = "RN_Gaming",
    ExperienceLockEnabled = false,
    AllowedPlaceIds = {},
    AutoGenerateOnServerStart = true,
    DefaultTerrainProfile = "FrozenDesertMoon",
    DefaultSeed = 515151,
    TerrainSeedMode = "Fresh",
    ClearManagedRegionBeforeGenerate = true,
    GeneratedEnvironmentFolderName = "GeneratedEnvironment",
    TerrainReservedFlatRadius = 308,
    TerrainReservedBlendRadius = 64,
    EnableNpcShop = true,
    EnableTycoon = true,
    EnableLineMeetGame = true,
    CurrencyName = "MoonCredits",
    StarterCurrency = 100,
}
