import json
import os
import tempfile
from pathlib import Path

from generate_game import build_rojo_project, populate_project


def test_generate_tycoon_template():
    with tempfile.TemporaryDirectory() as temp_dir:
        output_dir = Path(temp_dir)
        metadata = {
            "game_name": "TestTycoon",
            "template": "tycoon",
            "author": "Tester",
            "version": "0.1",
        }

        build_rojo_project(metadata["game_name"], output_dir)
        populate_project(output_dir, metadata)

        assert (output_dir / "default.project.json").exists()
        assert (output_dir / "server" / "MainServer.lua").exists()
        assert (output_dir / "client" / "MainClient.lua").exists()
        assert (output_dir / "shared" / "Config.lua").exists()
        assert (output_dir / "server" / "TycoonManager.lua").exists()
        assert (output_dir / "server" / "Leaderstats.lua").exists()

        with open(output_dir / "shared" / "Config.lua", "r", encoding="utf-8") as handle:
            content = handle.read()

        assert "TestTycoon" in content
        assert "AutoGenerated" not in content


def test_generate_waiting_in_line_template():
    with tempfile.TemporaryDirectory() as temp_dir:
        output_dir = Path(temp_dir)
        metadata = {
            "game_name": "LineGame",
            "template": "waiting_in_line",
            "author": "Tester",
            "version": "0.1",
        }

        build_rojo_project(metadata["game_name"], output_dir)
        populate_project(output_dir, metadata)

        assert (output_dir / "server" / "QueueManager.lua").exists()
        assert (output_dir / "client" / "WaitingLineClient.lua").exists()
        assert (output_dir / "shared" / "Config.lua").exists()


if __name__ == "__main__":
    test_generate_tycoon_template()
    test_generate_waiting_in_line_template()
    print("All tests passed.")
