import json
import os
import tempfile
from pathlib import Path

from generate_game import build_rojo_project, populate_project


def test_generate_tycoon_template():
    with tempfile.TemporaryDirectory() as temp_dir:
        output_dir = Path(temp_dir)
        metadata = {
            "game_name": "TestTycoon",
            "template": "tycoon",
            "author": "Tester",
            "version": "0.1",
            "group_id_literal": "846021713",
            "group_name_literal": "\"RN_Gaming\"",
        }

        build_rojo_project(metadata["game_name"], output_dir)
        populate_project(output_dir, metadata)

        assert (output_dir / "default.project.json").exists()
        assert (output_dir / "server" / "MainServer.lua").exists()
        assert (output_dir / "client" / "MainClient.lua").exists()
        assert (output_dir / "shared" / "Config.lua").exists()
        assert (output_dir / "server" / "TycoonManager.lua").exists()
        assert (output_dir / "server" / "Leaderstats.lua").exists()
        assert (output_dir / "server" / "WorldBuilder.lua").exists()
        assert (output_dir / "test" / "ModelLibrary.lua").exists()
        assert (output_dir / "test" / "BuildTestFolder.lua").exists()
        assert (output_dir / "test" / "SyncedModels" / "FloatingPine.model.json").exists()
        assert (output_dir / "test" / "SyncedModels" / "SkyIslandHub.model.json").exists()
        assert (output_dir / "studio" / "SpawnTestModels.plugin.lua").exists()
        assert (output_dir / "studio" / "SpawnTestModels.command.lua").exists()
        assert (output_dir / "INSTALL_AND_USAGE.md").exists()

        with open(output_dir / "default.project.json", "r", encoding="utf-8") as handle:
            project_config = json.load(handle)

        assert project_config["tree"]["ServerStorage"]["TestWorldModels"]["$path"] == "test"

        with open(output_dir / "shared" / "Config.lua", "r", encoding="utf-8") as handle:
            content = handle.read()

        assert "TestTycoon" in content
        assert "AutoGenerated" not in content
        assert "846021713" in content
        assert "\"RN_Gaming\"" in content

        with open(output_dir / "server" / "WorldBuilder.lua", "r", encoding="utf-8") as handle:
            world_builder = handle.read()

        assert "SkyIslandHub" in world_builder
        assert "SHOP -> RNG" in world_builder

        with open(output_dir / "test" / "BuildTestFolder.lua", "r", encoding="utf-8") as handle:
            test_builder = handle.read()

        assert "GeneratedModels" in test_builder
        assert "createFloatingPine" in test_builder

        with open(output_dir / "test" / "SyncedModels" / "SkyIslandHub.model.json", "r", encoding="utf-8") as handle:
            synced_preview = json.load(handle)

        assert synced_preview["ClassName"] == "Model"
        assert "Name" not in synced_preview

        with open(output_dir / "studio" / "SpawnTestModels.plugin.lua", "r", encoding="utf-8") as handle:
            plugin_script = handle.read()

        assert "Spawn Test Models" in plugin_script
        assert "TestWorldModels" in plugin_script
        assert "SyncedModels" in plugin_script

        with open(output_dir / "INSTALL_AND_USAGE.md", "r", encoding="utf-8") as handle:
            install_guide = handle.read()

        assert "SkyIslandHub" in install_guide
        assert "rojo serve --project default.project.json" in install_guide


def test_generate_waiting_in_line_template():
    with tempfile.TemporaryDirectory() as temp_dir:
        output_dir = Path(temp_dir)
        metadata = {
            "game_name": "LineGame",
            "template": "waiting_in_line",
            "author": "Tester",
            "version": "0.1",
        }

        build_rojo_project(metadata["game_name"], output_dir)
        populate_project(output_dir, metadata)

        assert (output_dir / "server" / "QueueManager.lua").exists()
        assert (output_dir / "client" / "WaitingLineClient.lua").exists()
        assert (output_dir / "shared" / "Config.lua").exists()
        assert (output_dir / "test" / "ModelLibrary.lua").exists()
        assert (output_dir / "test" / "SyncedModels" / "CloudPad.model.json").exists()
        assert (output_dir / "studio" / "SpawnTestModels.command.lua").exists()
        assert (output_dir / "INSTALL_AND_USAGE.md").exists()

        with open(output_dir / "shared" / "Config.lua", "r", encoding="utf-8") as handle:
            content = handle.read()

        assert "GroupId = nil" in content
        assert "GroupName = nil" in content


if __name__ == "__main__":
    test_generate_tycoon_template()
    test_generate_waiting_in_line_template()
    print("All tests passed.")
