return {
    GameName = "Mushroom Ruins Expanse",
    ExperienceName = "Mushroom Ruins Expanse",
    Architecture = "prompt-world-runtime-v1",
    Author = "AutoGenerated",
    Version = "0.1",
    ExperienceLockEnabled = false,
    AllowedPlaceIds = {},
    AutoGenerateOnServerStart = false,
    WorldGenerationMode = "PromptWorldRuntime",
    LegacyTerrainBootstrapDisabled = true,
}
