return {
    GameName = "Mushroom Ruins Expanse Smooth",
    ExperienceName = "Mushroom Ruins Expanse Smooth",
    Architecture = "prompt-smooth-world-runtime-v1",
    Author = "AutoGenerated",
    Version = "0.1",
    ExperienceLockEnabled = false,
    AllowedPlaceIds = {},
    AutoGenerateOnServerStart = false,
    WorldGenerationMode = "SmoothPromptWorldRuntime",
    WorldStyle = "smooth",
    LegacyTerrainBootstrapDisabled = true,
}
