return {
    GameName = "MyTycoonGame",
    ExperienceName = "MyTycoonGame",
    Architecture = "terrain-first-v1",
    Author = "Mikey",
    Version = "0.1",
    GroupId = 846021713,
    GroupName = "RN_Gaming",
    ExperienceLockEnabled = false,
    AllowedPlaceIds = {},
    AutoGenerateOnServerStart = true,
    DefaultTerrainProfile = "TemperateFrontier",
    DefaultSeed = 1337,
    TerrainProfileMode = "Random",
    TerrainSeedMode = "Fresh",
    TerrainVariantMode = "Remix",
    ClearManagedRegionBeforeGenerate = true,
    GeneratedEnvironmentFolderName = "GeneratedEnvironment",
    TerrainReservedFlatRadius = 308,
    TerrainReservedBlendRadius = 84,
    EnableNpcShop = true,
    EnableTycoon = true,
    EnableLineMeetGame = true,
    CurrencyName = "MoonCredits",
    StarterCurrency = 100,
}
