from __future__ import annotations

import argparse
import json
import shutil
import subprocess
from pathlib import Path

try:
    from export_world_pipeline_assets import write_world_pipeline_files
except ImportError:  # pragma: no cover - fallback for module execution styles
    from tools.export_world_pipeline_assets import write_world_pipeline_files


ARCHITECTURE_VERSIONS = {
    "blocky": "prompt-world-experience-v2",
    "smooth": "prompt-smooth-world-experience-v1",
}
PROMPT_WORLD_RUNTIME_VERSIONS = {
    "blocky": "prompt-world-runtime-v1",
    "smooth": "prompt-smooth-world-runtime-v1",
}
WORLD_GENERATION_MODES = {
    "blocky": "PromptWorldRuntime",
    "smooth": "SmoothPromptWorldRuntime",
}
TEMPLATE_DIRECTORIES = {
    "blocky": "prompt_world_runtime",
    "smooth": "prompt_world_runtime_smooth",
}
WORLD_STYLE_DESCRIPTIONS = {
    "blocky": "modular part-built terrain using snapped columns, cubes, and authored landmark parts",
    "smooth": "topographic heightfield generation using Workspace.Terrain, erosion passes, and chunked voxel writes",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a fresh Roblox world experience that generates original prompt-world geometry."
    )
    parser.add_argument("--name", required=True, help="Experience name.")
    parser.add_argument("--world-prompt", required=True, help="Plain-language world prompt.")
    parser.add_argument(
        "--world-style",
        choices=("blocky", "smooth"),
        default="blocky",
        help="Select the world-generation pipeline: blocky part-built terrain or smooth terrain-first runtime.",
    )
    parser.add_argument("--output-root", default="experiences", help="Parent directory for the generated experience.")
    parser.add_argument("--author", default="AutoGenerated", help="Author name.")
    parser.add_argument("--version", default="0.1", help="Version string.")
    parser.add_argument("--default-profile", default="TemperateFrontier", help="Default terrain profile for the scaffold.")
    parser.add_argument(
        "--generation-seed",
        type=int,
        default=None,
        help="Optional world generation seed. A fresh seed is created automatically when omitted.",
    )
    parser.add_argument("--force", action="store_true", help="Overwrite the target folder if it exists.")
    parser.add_argument("--skip-build", action="store_true", help="Skip `rojo build` after generation.")
    return parser.parse_args()


def create_terrain_scaffold(
    *,
    repo_root: Path,
    name: str,
    output_root: str,
    author: str,
    version: str,
    default_profile: str,
    force: bool,
) -> Path:
    command = [
        "python",
        str(repo_root / "tools" / "create_experience.py"),
        "--name",
        name,
        "--output-root",
        output_root,
        "--author",
        author,
        "--version",
        version,
        "--default-profile",
        default_profile,
    ]
    if force:
        command.append("--force")

    subprocess.run(command, cwd=repo_root, check=True)
    return (repo_root / output_root / name).resolve()


def build_project(project_root: Path, output_name: str) -> Path:
    build_dir = project_root / "build"
    build_dir.mkdir(parents=True, exist_ok=True)
    build_output = build_dir / f"{output_name}.rbxlx"
    subprocess.run(
        ["rojo", "build", "default.project.json", "-o", str(build_output)],
        cwd=project_root,
        check=True,
    )
    return build_output


def copy_prompt_world_runtime(*, repo_root: Path, project_root: Path, world_style: str) -> None:
    template_root = repo_root / "tools" / "templates" / TEMPLATE_DIRECTORIES[world_style]
    for relative_path in (
        Path("server/MainServer.server.lua"),
        Path("server/PromptWorldService.lua"),
    ):
        source_path = template_root / relative_path
        target_path = project_root / relative_path
        target_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source_path, target_path)


def remove_legacy_terrain_scaffold(*, project_root: Path) -> None:
    for relative_path in (
        Path("server/TerrainBootstrap.lua"),
        Path("server/terrain"),
        Path("client/MainClient.client.lua"),
        Path("shared/ExperienceGuard.lua"),
        Path("shared/TerrainProfiles.lua"),
        Path("terrain_profiles.json"),
        Path("README_GENERATED.md"),
        Path("INSTALL_AND_USAGE.md"),
        Path("art"),
        Path("studio"),
    ):
        target_path = project_root / relative_path
        if target_path.is_dir():
            shutil.rmtree(target_path, ignore_errors=True)
        elif target_path.exists():
            target_path.unlink()


def write_prompt_world_config(*, project_root: Path, name: str, author: str, version: str, world_style: str) -> None:
    config_path = project_root / "shared" / "Config.lua"
    config_text = (
        "return {\n"
        f"    GameName = {json.dumps(name, ensure_ascii=True)},\n"
        f"    ExperienceName = {json.dumps(name, ensure_ascii=True)},\n"
        f"    Architecture = {json.dumps(PROMPT_WORLD_RUNTIME_VERSIONS[world_style], ensure_ascii=True)},\n"
        f"    Author = {json.dumps(author, ensure_ascii=True)},\n"
        f"    Version = {json.dumps(version, ensure_ascii=True)},\n"
        "    ExperienceLockEnabled = false,\n"
        "    AllowedPlaceIds = {},\n"
        "    AutoGenerateOnServerStart = false,\n"
        f"    WorldGenerationMode = {json.dumps(WORLD_GENERATION_MODES[world_style], ensure_ascii=True)},\n"
        f"    WorldStyle = {json.dumps(world_style, ensure_ascii=True)},\n"
        "    LegacyTerrainBootstrapDisabled = true,\n"
        "}\n"
    )
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(config_text, encoding="utf-8")


def write_prompt_world_client(*, project_root: Path) -> None:
    client_path = project_root / "client" / "MainClient.client.lua"
    client_text = (
        'local Workspace = game:GetService("Workspace")\n'
        "\n"
        "local function reportPromptWorld()\n"
        '    local title = Workspace:GetAttribute("PromptWorldTitle")\n'
        '    local renderStyle = Workspace:GetAttribute("PromptWorldRenderStyle")\n'
        '    local terrain = Workspace:GetAttribute("PromptWorldTerrain")\n'
        "    if title and renderStyle and terrain then\n"
        '        print(string.format("[PromptWorld] %s (%s terrain, %s renderer)", title, tostring(terrain), tostring(renderStyle)))\n'
        "    end\n"
        "end\n"
        "\n"
        'Workspace:GetAttributeChangedSignal("PromptWorldTitle"):Connect(reportPromptWorld)\n'
        'Workspace:GetAttributeChangedSignal("PromptWorldRenderStyle"):Connect(reportPromptWorld)\n'
        'Workspace:GetAttributeChangedSignal("PromptWorldTerrain"):Connect(reportPromptWorld)\n'
        "reportPromptWorld()\n"
    )
    client_path.parent.mkdir(parents=True, exist_ok=True)
    client_path.write_text(client_text, encoding="utf-8")


def write_prompt_world_docs(*, project_root: Path, name: str, world_prompt: str, world_style: str) -> None:
    readme_path = project_root / "README_GENERATED.md"
    install_path = project_root / "INSTALL_AND_USAGE.md"

    readme_text = (
        f"# {name}\n\n"
        f"{name} is a prompt-world experience generated with the `{world_style}` world pipeline.\n\n"
        "## World style\n\n"
        f"- `{world_style}`: {WORLD_STYLE_DESCRIPTIONS[world_style]}\n\n"
        "## Generation policy\n\n"
        "- each regeneration uses a fresh procedural seed unless you explicitly pin `--generation-seed`\n"
        "- smooth worlds synthesize new terrain macro-shapes and new asset families instead of reusing fixed prefab landmarks\n"
        "- large smooth worlds use bounded hero-detail budgets and yielded generation steps to keep the runtime lighter\n\n"
        "## Generated files\n\n"
        "- `shared/WorldPromptSpec.lua` stores the parsed prompt result.\n"
        "- `shared/ModularWorldAssets.lua` stores the planning data and render-style metadata.\n"
        "- `server/PromptWorldService.lua` builds the world at edit time or runtime.\n"
        "- `prompt_world_experience.json` records the generated experience metadata.\n"
        "- `docs/world_prompt_runtime.json` keeps the JSON sidecar for inspection.\n"
        "- `docs/creator_store_asset_logs/*.xlsx` can store rolling Creator Store asset logs for the world.\n"
    )

    install_text = (
        f"# {name} Install And Usage\n\n"
        "This project is a prompt-world experience, not the older terrain scaffold.\n\n"
        "## Pipeline\n\n"
        f"- world style: `{world_style}`\n"
        f"- renderer: {WORLD_STYLE_DESCRIPTIONS[world_style]}\n"
        f"- source prompt: `{world_prompt}`\n\n"
        "## Fresh generation behavior\n\n"
        "- omit `--generation-seed` to force a new procedural terrain and asset pass on every regeneration\n"
        "- smooth worlds use a built-in optimization flow with topographic control maps, erosion passes, chunked voxel writes, and bounded hero detail\n\n"
        "## Open In Studio\n\n"
        "1. Open this project folder in your editor.\n"
        "2. Start Rojo from the project root:\n\n"
        "```powershell\n"
        "rojo serve --project default.project.json\n"
        "```\n\n"
        "3. Open the built place from `build/` or connect Studio with the Rojo plugin.\n\n"
        "## Regenerate From Prompt\n\n"
        "Regenerate the project from the repo root with:\n\n"
        "```powershell\n"
        f"python tools\\create_prompt_world_experience.py --name {json.dumps(name, ensure_ascii=True)} --world-style {world_style} --world-prompt {json.dumps(world_prompt, ensure_ascii=True)} --force\n"
        "```\n\n"
        "## Runtime Notes\n\n"
        "- `shared/Config.lua` keeps `AutoGenerateOnServerStart = false` by default so Studio does not rebuild unexpectedly.\n"
        "- `server/PromptWorldService.lua` is the active world builder for this experience.\n"
        "- `Workspace` attributes such as `PromptWorldTitle` and `PromptWorldRenderStyle` report the live generation result.\n"
        "- If you place ready-made Creator Store assets into the live world, record them with:\n\n"
        "```powershell\n"
        f"python tools\\log_creator_store_asset_usage.py --experience-root {json.dumps(str(project_root), ensure_ascii=True)}\n"
        "```\n\n"
        "- The asset log keeps only the latest 5 world workbooks and deletes older `.xlsx` files automatically.\n"
    )

    readme_path.write_text(readme_text, encoding="utf-8")
    install_path.write_text(install_text, encoding="utf-8")


def write_metadata(
    *,
    project_root: Path,
    name: str,
    world_prompt: str,
    generation_seed: int,
    build_output: Path | None,
    world_style: str,
) -> None:
    payload = {
        "name": name,
        "architecture": ARCHITECTURE_VERSIONS[world_style],
        "runtime": PROMPT_WORLD_RUNTIME_VERSIONS[world_style],
        "world_style": world_style,
        "world_prompt": world_prompt,
        "generation_seed": generation_seed,
        "build_output": str(build_output) if build_output else None,
    }
    (project_root / "prompt_world_experience.json").write_text(
        json.dumps(payload, indent=2, ensure_ascii=True) + "\n",
        encoding="utf-8",
    )


def main() -> int:
    args = parse_args()
    repo_root = Path(__file__).resolve().parent.parent

    project_root = create_terrain_scaffold(
        repo_root=repo_root,
        name=args.name,
        output_root=args.output_root,
        author=args.author,
        version=args.version,
        default_profile=args.default_profile,
        force=args.force,
    )

    written = write_world_pipeline_files(
        world_prompt=args.world_prompt,
        output_lua=project_root / "shared" / "WorldPromptSpec.lua",
        output_assets_lua=project_root / "shared" / "ModularWorldAssets.lua",
        output_json=project_root / "docs" / "world_prompt_runtime.json",
        generation_seed=args.generation_seed,
        pipeline_style=args.world_style,
    )
    copy_prompt_world_runtime(repo_root=repo_root, project_root=project_root, world_style=args.world_style)
    remove_legacy_terrain_scaffold(project_root=project_root)
    write_prompt_world_config(
        project_root=project_root,
        name=args.name,
        author=args.author,
        version=args.version,
        world_style=args.world_style,
    )
    write_prompt_world_client(project_root=project_root)
    write_prompt_world_docs(
        project_root=project_root,
        name=args.name,
        world_prompt=args.world_prompt,
        world_style=args.world_style,
    )

    build_output = None
    if not args.skip_build:
        build_output = build_project(project_root, args.name)

    write_metadata(
        project_root=project_root,
        name=args.name,
        world_prompt=args.world_prompt,
        generation_seed=written["generation_seed"],
        build_output=build_output,
        world_style=args.world_style,
    )

    print(
        json.dumps(
            {
                "project_root": str(project_root),
                "build_output": str(build_output) if build_output else None,
                "world_style": args.world_style,
                "world_prompt_spec": str(project_root / "shared" / "WorldPromptSpec.lua"),
                "modular_world_assets": str(project_root / "shared" / "ModularWorldAssets.lua"),
                "generation_seed": written["generation_seed"],
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
