import argparse
import subprocess
import sys
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a separate Roblox experience folder using the terrain-first scaffold."
    )
    parser.add_argument("--name", required=True, help="Game and experience name.")
    parser.add_argument("--output-root", default="experiences", help="Parent directory for the new experience folder.")
    parser.add_argument("--author", default="AutoGenerated", help="Author name.")
    parser.add_argument("--version", default="0.1", help="Initial version string.")
    parser.add_argument("--group-id", type=int, default=None, help="Optional Roblox group/community ID.")
    parser.add_argument("--group-name", default="", help="Optional Roblox group/community name.")
    parser.add_argument(
        "--place-id",
        action="append",
        type=int,
        default=[],
        help="Optional allowed PlaceId. Repeat for multiple places.",
    )
    parser.add_argument(
        "--default-profile",
        default="TemperateFrontier",
        help="Default terrain profile for the generated experience.",
    )
    parser.add_argument(
        "--default-seed",
        type=int,
        default=1337,
        help="Default terrain seed for the generated experience.",
    )
    parser.add_argument("--force", action="store_true", help="Overwrite the target directory if it exists.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo_root = Path(__file__).resolve().parent.parent
    output_dir = (repo_root / args.output_root / args.name).resolve()

    command = [
        sys.executable,
        str(repo_root / "generate_game.py"),
        "--game-name",
        args.name,
        "--experience-name",
        args.name,
        "--template",
        "terrain",
        "--output",
        str(output_dir),
        "--author",
        args.author,
        "--version",
        args.version,
        "--default-profile",
        args.default_profile,
        "--default-seed",
        str(args.default_seed),
    ]

    if args.group_id is not None:
        command.extend(["--group-id", str(args.group_id)])
    if args.group_name:
        command.extend(["--group-name", args.group_name])
    for place_id in args.place_id:
        command.extend(["--allowed-place-id", str(place_id)])
    if args.force:
        command.append("--force")

    subprocess.run(command, check=True, cwd=repo_root)
    print(f"Created experience scaffold at {output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
